### ISSUE TITLE
[Feature Request] docker 

### ISSUE THREAD

**Issue by breakingflower** [arcuru/chaz#8]
This project is referenced from the `matrix-chatgpt-bot` page (https://github.com/matrixgpt/matrix-chatgpt-bot), which exposes a simple dockerfile with some env variables to configure a matrix bot end-to-end. It's limited to only completions. 

I would love to switch to chaz but it's not clear from the instructions how you can do this. It would be great to have a snippet to add to my compose file of the matrix server to run chaz, incl. aichat. Aichat is primarily command line and I see that it exposes a proxy as well but I'm not sure how to connect the components. 

Can you please share some insight in how I can achieve this?

**Comment by arcuru** [comment]
Oh, I didn't realize it was pinged there, that's pretty cool.

As of today Chaz would be a bit annoying to package into a docker image, as I'd have to also package aichat and passthrough settings for model setup (i.e. bind mount the config files). It's certainly possible, but since i want to drop the dependency on aichat anyways it would be mostly wasted effort when I could spend the same time removing aichat in the first place.

When I get a couple free days to work on this project again I'll plan to setup a docker image as well, but I also need to do a few other things along with it to make things easier, including fixing both #3 and #5.

I'm planning to make these changes **next week,** but life has been pretty busy lately and these changes are at least a full day of work, probably more like 2-3 days to polish the interface.

After fixing #5 I will probably just run a public instance that will allow users to set their own API keys, which would make it very easy to get started but you'd need to trust that I wasn't stealing keys :shrug:

**Comment by arcuru** [comment]
I finally admitted to myself that I didn't know how complicated it would be to set up in docker, and it turns out I vastly overestimated the difficulty or I was just making excuses for not spending time here. The image is at `arcuru/chaz:main`. Until I push a new release you'll need to use the `main` tag.

Docker Hub link: https://hub.docker.com/r/arcuru/chaz

I've now added a docker image, and I'm running my own copy of `chaz` inside it. You do still need to configure both `aichat` and `chaz`, but this image includes both so it will run just fine.

Instructions are in the README: https://github.com/arcuru/chaz#docker
